# Generated by Django 2.1 on 2018-11-07 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('subject', models.CharField(choices=[('PSTAR', 'PSTAR'), ('PPL', 'Private Pilots License'), ('CPL', 'Commercial Pilots Licence'), ('IFR', 'Instrument Rating'), ('ATPL', 'Airline Pilots License')], default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
