# Generated by Django 2.1 on 2018-11-12 04:12

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_exam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='answer_at_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='incorrect_questions',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_order',
            field=models.CharField(default='', max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
