# Generated by Django 2.1 on 2018-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20181113_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
